spring.datasource.url: jdbc:h2:file:./camunda-h2-database

camunda.bpm.admin-user:
  id: admin
  password: admin
camunda.bpm.client:
  base-url: http://localhost:8080/engine-rest
  lock-duration: 10000
  subscriptions:
    ServiceReg:
      variable-names: id, name,lastname,age, status, docid
      process-definition-key: Lab5-process
    ServiceDoc:
      variable-name: name,lastname,age, docid
      process-definition-key: Lab5-process
    ServiceLab:
      variable-name: name,lastname,age
      process-definition-key: Lab5-process

logging:
  level:
    org:
      camunda:
        bpm:
          client: DEBUG

